rtl/cnn_accel_pkg.sv
rtl/postprocess/bias_add.sv
rtl/postprocess/relu.sv
rtl/postprocess/quantizer.sv
rtl/postprocess/output_saturate.sv
rtl/compute/mac_unit.sv
rtl/compute/mac_array_3x3.sv
rtl/compute/adder_tree.sv
rtl/compute/channel_accumulator.sv
rtl/compute/conv_engine.sv
rtl/compute/output_channel_array.sv
rtl/control/config_regs.sv
rtl/control/accel_controller.sv
rtl/control/perf_counters.sv
rtl/stream/stream_fifo.sv
rtl/stream/axis_input_if.sv
rtl/stream/axis_output_if.sv
rtl/buffer/activation_buffer.sv
rtl/buffer/weight_buffer.sv
rtl/buffer/line_buffer_3x3.sv
rtl/buffer/window_generator_3x3.sv
rtl/fpga/cnn_config_loader.sv
rtl/fpga/output_result_buffer.sv
rtl/fpga/streaming_cnn_core.sv
rtl/fpga/streaming_window_buffer.sv
rtl/cnn_accel_top.sv
tb/tb_cnn_accel_top_small.sv
